"""add_wiki_branches

Revision ID: 033_add_wiki_branches
Revises: 032_cleanup_legacy_source_pages
Create Date: 2026-06-01 11:28:43.406021
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '033_add_wiki_branches'
down_revision: Union[str, None] = '032_cleanup_legacy_source_pages'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wiki_branches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scope_type', sa.String(length=20), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('has_conflict', sa.Boolean(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wiki_branches_author_id', 'wiki_branches', ['author_id'], unique=False)
    op.create_index('ix_wiki_branches_status', 'wiki_branches', ['status'], unique=False)
    op.add_column('wiki_page_drafts', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.create_index('ix_wiki_drafts_branch_id', 'wiki_page_drafts', ['branch_id'], unique=False)
    op.create_foreign_key(None, 'wiki_page_drafts', 'wiki_branches', ['branch_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wiki_page_drafts', type_='foreignkey')
    op.drop_index('ix_wiki_drafts_branch_id', table_name='wiki_page_drafts')
    op.drop_column('wiki_page_drafts', 'branch_id')
    op.drop_index('ix_wiki_branches_status', table_name='wiki_branches')
    op.drop_index('ix_wiki_branches_author_id', table_name='wiki_branches')
    op.drop_table('wiki_branches')
    # ### end Alembic commands ###
